### ISSUE TITLE
Add more marker properties

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat#1080]
Spending quite some time testing the vcs markers has reminded me that for now, we can specify the **marker type, size and color**, but it would be quite useful to be able to also specify the following:
- edge color (except for _star_, _cross_ or markers where it does not make sense)
- edge thickness
- more precise size control than in 1.5.1
- support the same marker types (and names) as in matplotlib

I have implemented edge color and thickness by _overlaying 2 markers of different color and size_, as can be seen in the following figure generated for the IPCC report, but **it was quite painful**
![deep_ocean](https://cloud.githubusercontent.com/assets/2785573/6374088/f446eb04-bd0e-11e4-9ce6-c511c898b62d.png)

The following ones were also made for IPCC. The top 2 were made with vcs (1.x), using the _overlay 2 markers to simulate an edge_ and the third was made with matplotlib+basemap. Guess which one has the nicest markers (you will have to click to get the full size picture).

Hopefully, the new way of rendering the plots in 2.x will make it possible to dramatically increase the output quality! In vcs we trust!

**Note that supporting non linear projection forthe data AND the markers AND the meridians/parallels (and the text objects, etc) is vital if we want to be able to keep on making plot like the following**

![tas_21_models_margo_110915_b](https://cloud.githubusercontent.com/assets/2785573/6374422/0df05d18-bd11-11e4-910b-b4d3cd986682.png)

![tas_21_bart_margo_misc_120614_01](https://cloud.githubusercontent.com/assets/2785573/6374439/1fce6c46-bd11-11e4-9090-56fa93bf004a.png)

![tas_21_bart_margo_misc_regions_20130724_1525](https://cloud.githubusercontent.com/assets/2785573/6374446/351c352e-bd11-11e4-9c69-82fdd5c261ba.png)

**Comment by durack1** [comment]
@jypeter are the scripts that generated these plots also available to be added to the test suite - seems like these would be another useful test of the software to catch changes as they're happening..

**Comment by jypeter** [comment]
Unfortunately, these are long and dirty scripts that will not be suitable for the test suite. I would have to devise standalone versions (as I have done for the text or marker problems), but I'm already getting so much behind schedule reporting all this... :(

**Comment by doutriaux1** [comment]
@jypeter I'm not sure we have cycles for this, feel free to fork and provide an update.
