### ISSUE TITLE
Template edits not showing up in recorded commands

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#1222]
If i edit template within gui, then the modifications do not show up in recorded commands.

**Comment by doutriaux1** [comment]
@chaosphere2112 feel free to reassign

**Comment by chaosphere2112** [comment]
@doutriaux1 I found where the logic to add template info to the sample scripts would go ([in here](https://github.com/UV-CDAT/VisTrails/blob/3e92adbe6ff095c1db29d2c155ba3b55a9d88ff3/vistrails/packages/uvcdat_cdms/pipeline_helper.py#L783-L883)); adding it does look like a fair bit of work, though. I'll put this off for now, leaving this comment mostly as a reminder to myself.

**Comment by doutriaux1** [comment]
@chaosphere2112 if think you're right, we hecked that the png is produced correctly, so for 2.2 I "think" it's ok. Moving milestone to 2.3. @williams13 please let us know if you feel this needs to be in 2.2

**Comment by chaosphere2112** [comment]
Will resolve in GUI refactor
