### ISSUE TITLE
wind barb support

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#1264]
vector.type= "barbs" should be drawing wind barbs

**Comment by dlonie** [comment]
Do you have an example of this? I'm not sure what a 'wind barb' looks like.

**Comment by doutriaux1** [comment]
```
u=f("u")
v=f("u")
vec = x.createvector()
vec.type="barbs"
x.plot(u[...,::2,::2],v[...,::2,::2],vec)
x.png("barbs")
x.clear()
vec.type="solidarrows"
x.plot(u[...,::2,::2],v[...,::2,::2],vec)
x.png("solid")
```
BARBS:
![barbs](https://cloud.githubusercontent.com/assets/2781425/7459537/96fb4b5c-f251-11e4-9ea0-db6cd80ce8b8.png)
SOLID:
![solid](https://cloud.githubusercontent.com/assets/2781425/7459539/a01ca708-f251-11e4-8d9d-

**Comment by doutriaux1** [comment]
@dlonie old code should be at: https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs_legacy/Src/library/vectors.c

**Comment by dlonie** [comment]
So 

- A barb has two parts, a backbone and a set of ticks.
- The backbone points in the direction of the vector with the ticks on the "tail" end.
- The number of barbs represents the magnitude of the vector.
- 0 magnitude vectors are rendered as a square.

Anything I'm missing? Some of the tick marks appear slanted in different ways. Is that a rendering artifact, or is it meaningful?

**Comment by doutriaux1** [comment]
@dlonie I think the "salnt" is due to positive vs negative. Also I need to look into what the "reference" attribute on a vector graphic method does. But it might be related to barbs. @potter2 can you comment on this? @williams13 you wrote this a loooong time ago, do you remember?
