### ISSUE TITLE
Prototype context 2d in pure VTK script

### ISSUE THREAD

**Issue by aashish24** [CDAT/cdat#1407]

**Comment by doutriaux1** [comment]
@aashish24 what is that exactly? Also, please can you add a milestone?

**Comment by dlonie** [comment]
Still got a ways to go, but some progress on a local branch:

<img width="303" alt="context" src="https://cloud.githubusercontent.com/assets/58744/9256837/0c77a6ce-41c0-11e5-8a53-4257b3b7daa1.png">

This is currently built via a very manual process in the testing script, next step is to wrap it up with a nice interface so it can be easily configured.

**Comment by aashish24** [comment]
This is looking awesome!!!! I am assuming that we can set the precision on the labels easily.

**Comment by dlonie** [comment]
vtkAxis autodetects the precision based on the range of the data so that each tick shows something unique. This can be overridden, though.

**Comment by doutriaux1** [comment]
Nice! We (I guess @sankhesh and @doutriaux1 ) just need to link this back to the template and graphics methods once you ironed it out! That's great!

**Comment by dlonie** [comment]
More progress, I have a vtkContextArea class that takes care of setting up the clip/transform/axes/grid/etc. Just need to get things working on the OpenGL2 backend, which is looking to be rather tricky. Hope to finish it up next week.

vtkContextArea API: https://gitlab.kitware.com/dlonie/vtk/blob/c362e6b618425e3b03f34e51ac7535ebfffcad71/Charts/Core/vtkContextArea.h
Example Usage: https://gitlab.kitware.com/dlonie/vtk/blob/c362e6b618425e3b03f34e51ac7535ebfffcad71/Charts/Core/Testing/Cxx/TestPropItem.cxx#L123

**Comment by aashish24** [comment]
Nice @dlonie. We don't need OpenGl2 stuff yet (although it would be nice to get it done). If you are far enough, then i would suggest keep going with it. 

Thanks

**Comment by dlonie** [comment]
The OpenGL2 implementations are needed so it can be merged into VTK -- supporting the new backend isn't really optional.

@doutriaux1 @sankhesh @aashish24 I've pushed the new vtkContext2D stuff to UV-CDAT/VTK#6 

This isn't ready to merge (There is a known issue with the stencil buffer on macs that I'm trying to track down), but we can start porting code over to it and begin finalizing the API/behaviors while I track down the mac bug.

**Comment by doutriaux1** [comment]
thanks @dlonie that's good news overall.

**Comment by aashish24** [comment]
thanks @dlonie

**Comment by aashish24** [comment]
@danlipsa
