### ISSUE TITLE
Construct higher-res dots (circles for VCS)

### ISSUE THREAD

**Issue by aashish24** [CDAT/cdat#1439]

**Comment by jypeter** [comment]
Well, not just dots! **All the markers should look nice**, both on *raster* (png) and *vector* (pdf) output

See the matplotlib example below. You get a nice png, AND you can zoom the pdf output as much as you want...

http://matplotlib.org/examples/lines_bars_and_markers/marker_reference.html

What could be useful would be a way to specify the color and thickness of the marker's edge (the way you can do it in matplotlib). See #1080

**Comment by aashish24** [comment]
@jypeter if you export as PDF then should look nice. The issue with circles is that you can set the resolution and currently it is set to low resolution geometry which make them look pixelated.

**Comment by aashish24** [comment]
@sankhesh for now, I have assigned it a low label as we have other bugs to fix.

**Comment by sankhesh** [comment]
This branch in VTK adds support for resolution for 2D circular glyphs: https://gitlab.kitware.com/vtk/vtk/merge_requests/375

**Comment by doutriaux1** [comment]
@sankhesh on your "would be nice list" should we move it to 3.0?

**Comment by doutriaux1** [comment]
migrated
