### ISSUE TITLE
Vector animation implementation needs finishing

### ISSUE THREAD

**Issue by allisonvacanti** [CDAT/cdat#1451]
#1450 removes the VTK pipeline rebuilding code from VTKPlots.py, and with it goes a partial implementation for vector plots. I've ported this bit into unmerged commit 1ffc97a6e029d3988be8b26df3b4713ffa083181 (branch https://github.com/UV-CDAT/uvcdat/tree/update_input_vector), made sure a complete pipeline would persist through the animation steps, and added a test.

**Comment by doutriaux1** [comment]
migrated to vcs
