### ISSUE TITLE
In UVCDAT GUI, have variable selection pin apply to averaging option too.

### ISSUE THREAD

**Issue by cameronsmith1** [CDAT/cdat#1469]
When sub-selecting a variable, there is a 'pin' so that the same range can be easily applied to many variables.   At the moment, the pin only preserves the selected range, and not the state of the 'averaging' setting.   I think users will overwhelmingly expect and prefer to have the pin apply to both the range and the averaging.

**Comment by cameronsmith1** [comment]
I was just got caught by this problem, and was about to report it, when I realized that I had reported it last year.  I still think this should be changed.

**Comment by doutriaux1** [comment]
@chaosphere2112 @sampsonbryce @mattben we should definitely implement this in vcdat.

**Comment by chaosphere2112** [comment]
@cameronsmith1 @doutriaux1 Yup, I agree. We'll make sure this goes into VCDAT.

**Comment by mattben** [comment]
moved to vcdat
