### ISSUE TITLE
update should try not to clear

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#1482]
in VTKPlot.py the update function clears all display and redraws everything.

Now we have the update_input function that in most case (no change to template or graphic method) would be faster and would prevent a clear.

@dlonie I believe with your refactoring this update function should eventually be able to take advantage of the new pipeline even if a graphic method changed, right?

**Comment by dlonie** [comment]
@doutriaux1 I'm not sure. I see the `update` function in VTKPlots.py, but it's undocumented and I'm not sure what it's supposed to do or what it's updating.

The pipeline classes allow an existing graphics method to re-execute if a data source changes (e.g. changing time steps) or the rendering parameters change (e.g. a window resize) without the need to rebuild the pipeline from scratch.

**Comment by doutriaux1** [comment]
migrated to vcs
