### ISSUE TITLE
Ocean data masks not displaying correctly (VCS)

### ISSUE THREAD

**Issue by durack1** [CDAT/cdat#1832]
The ocean land/sea masks are not displaying properly in VCS - contrast the attached VCS output (first) and the same data plotted using ferret (second).

The file used is: `/cmip5_css02/data/cmip5/output1/CSIRO-BOM/ACCESS1-0/1pctCO2/fx/ocean/fx/r0i0p0/areacello/1/areacello_fx_ACCESS1-0_1pctCO2_r0i0p0.nc`
![cmip5 access1-0 1pctco2 r0i0p0 fx ocn fx areacello ver-1](https://cloud.githubusercontent.com/assets/3229632/13094757/bf4fc990-d4c1-11e5-84f5-fdb053b71534.png)
![cmip5 access1-0 1pctco2 r0i0p0 fx ocn fx areacello ver-1-ferret](https://cloud.githubusercontent.com/assets/3229632/13094759/c2140e5c-d4c1-11e5-846e-17fe3fa7389e.gif)

**Comment by doutriaux1** [comment]
use .filled(0.0)to have vcs treat it as a regular 2D array.

**Comment by doutriaux1** [comment]
migrated to vcs
