### ISSUE TITLE
Streamlines Graphics Method

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/cdat#1925]
We need a graphics method for creating a streamlines plot

**Comment by aashish24** [comment]
@danlipsa let's talk about it next week.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 What about using vector.py, vc.type to specify that we want streamlines?
So far we have: 
0 - 'arrow head'
1 - 'wind barbs'
2 - 'solid arrow head'
We can add a 3 - 'streamlines'.
I might need to add other parameters specific to vectors.
Comments?

**Comment by danlipsa** [comment]
Or maybe have a streamline graphics method similarly with the vector graphics methods. This seems to fit better existing API (and code).
