### ISSUE TITLE
vcs should rember the original value stored by the user

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#2010]
example

``` python
>>> gm  = x.createisoline()
>>> gm.line= ['dot','dash']
>>> gm.line
['dot', 'dash']
>>> gm.line= [1,2,3]
>>> gm.line
['dash', 'dot', 'dash-dot']
>>> 
```

**Comment by danlipsa** [comment]
@doutriaux1 This case is not too bad as there is a one-to-one mapping between numbers and line type descriptions, isn't it?

**Comment by danlipsa** [comment]
Also look at 
datawc_ being changed to cdtime.reltime for time axis. See
https://github.com/UV-CDAT/uvcdat/pull/2007

**Comment by doutriaux1** [comment]
@danlipsa yes #2007 is the most disturbing, but we might as well fix it everywhere so it consistently return to the user what it stored.

**Comment by doutriaux1** [comment]
migrated
