### ISSUE TITLE
creating pngs in background mode leaks (much less) memory

### ISSUE THREAD

**Issue by danlipsa** [CDAT/cdat#2040]
This is a continuation of
https://github.com/UV-CDAT/uvcdat/issues/1397
While our VTK fix improved the leak considerably (from 500 MB to 6MB for 500 iterations) there is still a memory increase. It is possible that certain resources are still leaked.
More investigation is required to create a test that pinpoints the problem.

Here is the test program I used on linux:
[png-memory.zip](https://github.com/UV-CDAT/uvcdat/files/342288/png-memory.zip)

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 I created this follow-up issue if we want to dig more into this.

**Comment by durack1** [comment]
@danlipsa I think this should be reviewed alongside #1424 as the problems may be linked. I'm just running my #1424 test script against `2.6.0` and it seems there are still quite a number of problems remaining.. @chaosphere2112 pinging you here

**Comment by chaosphere2112** [comment]
#1424 will remain unresolved for now, I wasn't able to get a pull request in before the release. I'll try and get something together shortly so it can go into nightly builds. For the present, I'd recommend just using the "donotstoredisplay" argument.

**Comment by durack1** [comment]
@chaosphere2112 I just ran the script with `donotstoredisplay=True` and this is the result (also turned off the `delFudge` tweak - it seems things are still very broken, 2315 seconds and 24GB to plot a 3 panel figure seems a little extreme to me:
```
UV-CDAT version:      v2.5.0-388-g9d06e08
UV-CDAT prefix:       /export/durack1/anaconda2/envs/uvcdat
delFudge:             False
Background graphics:  True
00001 processing: 1870-01 sic     Time: 07.361 secs; Max mem: 1.118 GB PyObj#: 0092480;
00002 processing: 1870-02 sic     Time: 05.179 secs; Max mem: 1.551 GB PyObj#: 0093276;
00003 processing: 1870-03 sic     Time: 04.296 secs; Max mem: 1.595 GB PyObj#: 0093771;
00004 processing: 1870-04 sic     Time: 05.091 secs; Max mem: 1.638 GB PyObj#: 0094265;
00005 processing: 1870-05 sic     Time: 04.540 secs; Max mem: 1.680 GB PyObj#: 0094760;
00006 processing: 1870-06 sic     Time: 06.039 secs; Max mem: 1.723 GB PyObj#: 0095255;
00007 processing: 1870-07 sic     Time: 05.725 secs; Max mem: 1.766 GB PyObj#: 0095750;
00008 processing: 1870-08 sic     Time: 06.299 secs; Max mem: 1.809 GB PyObj#: 0096245;
00009 processing: 1870-09 sic     Time: 05.634 secs; Max mem: 1.852 GB PyObj#: 0096740;
00010 processing: 1870-10 sic     Time: 05.728 secs; Max mem: 1.895 GB PyObj#: 0097235;
...
00015 processing: 1871-03 sic     Time: 09.083 secs; Max mem: 2.110 GB PyObj#: 0099710;
...
00020 processing: 1871-08 sic     Time: 14.018 secs; Max mem: 2.325 GB PyObj#: 0102185;
...
00025 processing: 1872-01 sic     Time: 16.569 secs; Max mem: 2.539 GB PyObj#: 0104360;
...
00050 processing: 1874-02 sic     Time: 37.991 secs; Max mem: 3.614 GB PyObj#: 0116882;
...
00075 processing: 1876-03 sic     Time: 69.513 secs; Max mem: 4.691 GB PyObj#: 0128791;
...
00100 processing: 1878-04 sic     Time: 115.786 secs; Max mem: 5.766 GB PyObj#: 0140544;
...
00150 processing: 1882-06 sic     Time: 210.337 secs; Max mem: 7.910 GB PyObj#: 0164830;
...
00200 processing: 1886-08 sic     Time: 352.287 secs; Max mem: 10.059 GB PyObj#: 0188492;
...
00250 processing: 1890-10 sic     Time: 535.705 secs; Max mem: 12.187 GB PyObj#: 0211198;
...
00300 processing: 1894-12 sic     Time: 762.082 secs; Max mem: 14.338 GB PyObj#: 0234080;
...
00350 processing: 1899-02 sic     Time: 1055.304 secs; Max mem: 16.458 GB PyObj#: 0256807;
...
00400 processing: 1903-04 sic     Time: 1338.400 secs; Max mem: 18.611 GB PyObj#: 0280157;
...
00450 processing: 1907-06 sic     Time: 1887.651 secs; Max mem: 20.769 GB PyObj#: 0303351;
...
00500 processing: 1911-08 sic     Time: 2166.998 secs; Max mem: 22.929 GB PyObj#: 0326837;
...
00525 processing: 1913-09 sic     Time: 2315.047 secs; Max mem: 24.007 GB PyObj#: 0337186;
```

**Comment by chengzhuzhang** [comment]
Hi Charles @charlesdoutriaux ,

Here is our repo for acme_diags:
https://github.com/zshaheen/acme_diags
Here is the documentation to run the package on aims4:

https://github.com/zshaheen/acme_diags/blob/master/docs/quick-guide-aims4.ipynb
make sure in myparams.py, set backend = 'vcs'

If you do below (which create a lot of pngs)
set5_driver.py -p myparams.py 

Process gets slower and slower. No problem for cartopy backend...

Also we have this libGL error when testing on aims4. 
@zshaheen

**Comment by durack1** [comment]
@chengzhuzhang does your behavior look similar to https://github.com/UV-CDAT/uvcdat/issues/1424#issuecomment-114927604? So you get a progressive slow down after each loop step?

Oh and @doutriaux1 is the best github handle for Chucky (@charlesdoutriaux is his personal/non-work handle)

**Comment by zshaheen** [comment]
@chengzhuzhang I'm fairly sure we're getting the libGL error b/c we **aren't** using vcs-nox. I'll try with that and we'll see what's good.

@doutriaux1 No need to run it. If we're still getting errors, we'll let you know.

**Comment by chengzhuzhang** [comment]
@durack1 Thank you for the hint in poking Chucky :)
We will update here if vcs-nox can fix the libGL and the slowness.
