### ISSUE TITLE
ctest output wrong links to cdash

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#2083]
when travis runs the log to cdash is useless
travis url is:

https://travis-ci.org/UV-CDAT/uvcdat/jobs/150981350

```
Submit files (using http)
   Using HTTP submit method
   Drop site:http://open.cdash.org/submit.php?project=UV-CDAT
   Uploaded: /home/travis/build/UV-CDAT/_build/Testing/20160809-1914/Build.xml
   Uploaded: /home/travis/build/UV-CDAT/_build/Testing/20160809-1914/Configure.xml
   Uploaded: /home/travis/build/UV-CDAT/_build/Testing/20160809-1914/Test.xml
   Submission successful
Errors while running CTest
```

Clicking on the link to cdash does not take me to the actual page where I can see the failed tests.

**Comment by aashish24** [comment]
@doutriaux1 is this still the case?

**Comment by doutriaux1** [comment]
yes. Also ctest -D Experimental does not always post into the Experimental section...

**Comment by aashish24** [comment]
weird.. looking into it now.

**Comment by aashish24** [comment]
> yes. Also ctest -D Experimental does not always post into the Experimental section...

This is the case for your machine or somewhere else?

**Comment by aashish24** [comment]
http://open.cdash.org/submit.php?project=UV-CDAT

> Clicking on the link to cdash does not take me to the actual page where I can see the failed tests.

Are you referring to this link @doutriaux1 ? 
http://open.cdash.org/submit.php?project=UV-CDAT

Thanks,

**Comment by jasonb5** [comment]
Closing as I do not believe we've pushed an update in quite some time.

**Comment by doutriaux1** [comment]
@jasonb5 yes this is pre-conda when we used to build everything (including external deps)  from sources

**Comment by jasonb5** [comment]
@doutriaux1 Ah good to know, thanks.
