### ISSUE TITLE
UVCDAT environment  setting

### ISSUE THREAD

**Issue by pywu** [CDAT/cdat#2140]
Hello, I installed UVCDAT 2.6 using anaconda conda. The installation went smoothly  on MacOSX.

After source  activate uvcdat,  import cdat_info. is OK, but import vcs with error message like:

>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wanliwu/anaconda3/envs/uvcdat/lib/python2.7/site-packages/vcs/__init__.py", line 31, in <module>
    from utils import *  # noqa
  File "/Users/wanliwu/anaconda3/envs/uvcdat/lib/python2.7/site-packages/vcs/utils.py", line 3, in <module>
    import cdtime
ImportError: dlopen(/Users/wanliwu/anaconda3/envs/uvcdat/lib/python2.7/site-packages/cdtime.so, 2): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: /Users/wanliwu/anaconda3/envs/uvcdat/lib/libjasper.1.0.0.dylib
  Reason: image not found

I was wondering if I need some environment variable  to set. please advise.  I tried using python, which also came with error message:
----> 1 import vcs

/Users/wanliwu/anaconda3/envs/uvcdat/lib/python2.7/site-packages/vcs/__init__.py in <module>()
     26 next_canvas_id = 1
     27 import cdat_info  # noqa
---> 28 prefix = cdat_info.get_prefix()
     29 sample_data = cdat_info.get_sampledata_path()
     30 cdat_info.pingPCMDIdb("cdat", "vcs")

AttributeError: module 'cdat_info' has no attribute 'get_prefix'

Thanks in advance for helping.

Wanli
wu80012@gmail.com

**Comment by aashish24** [comment]
Wanli looks like an issue with libjpeg. @doutriaux1 any insight?

**Comment by aashish24** [comment]
@Wanli I can confirm that it seems to broken on Linux as well.

**Comment by aashish24** [comment]
@Wanli @doutriaux1 looks like we have a bad conda binary on binstar.

**Comment by pywu** [comment]
Dear Aashish,

Thank you taking looks at the issue. I tried the highlyuvcdat with conda.
It went smoothly.  uvcdat now works fine on my MacBook Pro. Only trouble is
that after uvcdat, my normal anaconda  (python 3.5) does not function well,
for example'  import pandas as pd' failed import (uvcdat is deactivated).
Any ideas?

Thanks,

Wanli

On Tue, Nov 15, 2016 at 2:19 PM, Aashish Chaudhary <notifications@github.com

**Comment by aashish24** [comment]
> Dear Aashish,
> 
> Thank you taking looks at the issue. I tried the highlyuvcdat with conda.
> It went smoothly.  uvcdat now works fine on my MacBook Pro. Only trouble is

This is great news, credit goes to @doutriaux1 

> that after uvcdat, my normal anaconda  (python 3.5) does not function well,
> for example'  import pandas as pd' failed import (uvcdat is deactivated).
> Any ideas?

Can you post the complete message here?
