### ISSUE TITLE
opendap

### ISSUE THREAD

**Issue by glpotter** [CDAT/cdat#2166]
Has anyone tried opendap recently?
Here is an address that I know works but cdat won't open it.

https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/reanalysis/MERRA/mon/atmos/ua.ncml
I did delete the .dodsrc file

Grads opens it fine..

**Comment by doutriaux1** [comment]
hum.. it's https:// I wonder if that is the issue. What do you think @dnadeau4 ?

**Comment by doutriaux1** [comment]
here at the lab I can't see it, even in a browser i get:
```
Error {
    code = 400;
    message = "Unrecognized request";
};
```

**Comment by doutriaux1** [comment]
@glpotter do you mind close this if it works for you and if not post it on cdms repo for @dnadeau4 to take a look? Thanks

**Comment by dnadeau4** [comment]
@glpotter this works now.

```python
import cdms2

f=cdms2.open("https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/ua.ncml
f.listvariables()
['time_bnds', 'lat_bnds', 'ua', 'lon_bnds']
data=f['ua']
data.shape
(446, 42, 361, 540)
data[0,0,:]
ua
masked_array(
  data=[[--, --, --, ....
```
