### ISSUE TITLE
ImportError: No module named vtkGeovisCorePython/vtkIOFFMPEGPython

### ISSUE THREAD

**Issue by puneet336** [CDAT/cdat#2200]
Hi all, 
I have installed uvcdat using anaconda v 4.3.0 on CentOS 7. 

```
user@machine:~> export PATH=/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/bin:$PATH
user@machine:~> source activate myuvcdat
(myuvcdat) user@machine:~> python
Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:16:05)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
readline: /etc/inputrc: line 19: term: unknown variable name
>>> import cdat_info
>>> import cdms2
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/envs/myuvcdat/lib/python2.7/site-packages/vcs/__init__.py", line 92, in <module>
    from utils import *  # noqa
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/envs/myuvcdat/lib/python2.7/site-packages/vcs/utils.py", line 38, in <module>
    import vtk
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/envs/myuvcdat/lib/python2.7/site-packages/vtk/__init__.py", line 87, in <module>
    from .vtkGeovisCore import *
  File "/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/envs/myuvcdat/lib/python2.7/site-packages/vtk/vtkGeovisCore.py", line 9, in <module>
    from vtkGeovisCorePython import *
ImportError: No module named vtkGeovisCorePython
>>>
```

I have installed uvcdat from instructions mentioned at - https://github.com/CDAT/cdat/wiki/install.
Installation procedure/terminal log is attached.

Please let me know if any further information is required from my end.
[uvcdat_install.txt](https://github.com/CDAT/cdat/files/1832945/uvcdat_install.txt)

**Comment by doutriaux1** [comment]
@puneet336 as mentioned in my previous comment, you need to downgrade `proj4`

```
conda install -f -c conda-forge "proj4<5"
```

**Comment by puneet336** [comment]
Thank you for suggestion. It downgrading proj4 fixed the import issue.
 

[user@machine1 ~]$ export PATH=/home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/bin:$PATH                                                                    [user@machine1 ~]$ conda install -f -c conda-forge "proj4<5"^C
[user@machine1 ~]$ source activate myuvcdat
(myuvcdat) [user@machine1 ~]$ conda install -f -c conda-forge "proj4<5"
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/apps/SiteSoftwares/gnu/ANACONDA2/4.3.0_alt/envs/myuvcdat:

The following packages will be DOWNGRADED:

    proj4: 5.0.0-0 conda-forge --> 4.9.3-5 conda-forge

Proceed ([y]/n)? y

proj4-4.9.3-5. 100% |#################################################################################################################| Time: 0:00:02   1.68 MB/s
(myuvcdat) [user@machine1 ~]$

(myuvcdat) user@machine1:~> python
Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:16:05)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdms2, cdat_info
>>> import vcs
>>>
>>>
>>>

**Comment by puneet336** [comment]
Hi,
I tried installing cdat-8. installation command - 
`[user@machine1 INSTALLATION_RELATED]$ conda create -n cdat8 -c conda-forge -c cdat xmgrace cdat
`
terminal log is attached.

The error message i get - 
```
(cdat8)  user@machine1:~> python
Python 2.7.14 | packaged by conda-forge | (default, Mar 30 2018, 18:16:04)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
readline: /etc/inputrc: line 19: term: unknown variable name
>>> import vcs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/applications/SiteSoftwares/gnu/ANACONDA2/5.1.0/envs/cdat8/lib/python2.7/site-packages/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/home/applications/SiteSoftwares/gnu/ANACONDA2/5.1.0/envs/cdat8/lib/python2.7/site-packages/vcs/utils.py", line 39, in <module>
    import vtk
  File "/home/applications/SiteSoftwares/gnu/ANACONDA2/5.1.0/envs/cdat8/lib/python2.7/site-packages/vtk/__init__.py", line 95, in <module>
    from .vtkIOFFMPEG import *
  File "/home/applications/SiteSoftwares/gnu/ANACONDA2/5.1.0/envs/cdat8/lib/python2.7/site-packages/vtk/vtkIOFFMPEG.py", line 9, in <module>
    from vtkIOFFMPEGPython import *
ImportError: No module named vtkIOFFMPEGPython
>>> import cdms2, cdat_info
>>>
```

The version of proj4 is < 5.

```
(cdat8)  user@machine1:~> conda list|grep proj4
proj4                     4.9.3                         5    conda-forge
(cdat8)  user@machine1:~>

```

What could be the possible reason behind this issue?
[install.txt](https://github.com/CDAT/cdat/files/1980470/install.txt)

**Comment by doutriaux1** [comment]
conda-forge update ffmpeg. For now please do this in your cdat environement:
```
conda install -f -c conda-forge "ffmpeg<4"
```

**Comment by doutriaux1** [comment]
I am in the process f recompiling vtk-cdat against the newest ffmpeg.

**Comment by puneet336** [comment]
with ffmpeg<4 , imports are now working fine.
Thanks again..
