### ISSUE TITLE
should we be able to upgrade an existing cdat environment?

### ISSUE THREAD

**Issue by sashakames** [CDAT/cdat#2201]
(root) ames4ml:~ ames4$ source activate cdat
(cdat) ames4ml:~ ames4$ conda install -c cdat/label/v80 -c conda-forge cdat
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - cdat -> thermo >2.12
  - cdat -> wk >2.12
  - uvcdat -> thermo ==2.12
  - uvcdat -> vcsaddons ==2.12
  - uvcdat -> wk ==2.12

What do you do now?  or must you start from scratch?

**Comment by doutriaux1** [comment]
I think I forgot to apply the labels, please try again. Thanks for testing it @sashakames

**Comment by jasonb5** [comment]
Closing as upgrading CDAT releases is not supported.
