### ISSUE TITLE
using conda to install cdutil results in unexpected python 3.6 upgrade from 2.7

### ISSUE THREAD

**Issue by sashakames** [CDAT/cdat#2202]
# conda activated in path
$ conda create -n cdutiltest -c conda-forge -c cdat cdutil

The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py36_0         conda-forge
    ca-certificates: 2018.1.18-0           conda-forge
    cdat_info:       8.0-py36_0            conda-forge
    cdms2:           3.0-py36_5            conda-forge
    cdtime:          3.0-py36_0            conda-forge
    cdutil:          8.0-py36_1            conda-forge
    certifi:         2018.1.18-py36_0      conda-forge
    cffi:            1.11.5-py36_0         conda-forge
    chardet:         3.0.4-py36_0          conda-forge
    clapack:         3.2.1-0               conda-forge
    cryptography:    2.2.1-py36_0          conda-forge
    curl:            7.59.0-0              conda-forge
    distarray:       2.12.2-py36_0         conda-forge
    esmf:            7.1.0r-0              conda-forge
    esmpy:           7.1.0r-py36_1         conda-forge
    expat:           2.2.5-0               conda-forge
    future:          0.16.0-py36_0         conda-forge
    g2clib:          1.6.0-5               conda-forge
    genutil:         8.0-py36_0            conda-forge
    hdf4:            4.2.13-0              conda-forge
    hdf5:            1.10.1-2              conda-forge
    idna:            2.6-py36_1            conda-forge
    intel-openmp:    2018.0.0-8                       
    jasper:          1.900.1-4             conda-forge
    jpeg:            9b-2                  conda-forge
    krb5:            1.14.2-0              conda-forge
    lapack:          3.6.1-1               conda-forge
    libcdms:         3.0-1                 conda-forge
    libcf:           1.0.1-py36_1          conda-forge
...
...

(base) [ames4@esgf-dev1 ~]$ conda activate cdutiltest
(cdutiltest) [ames4@esgf-dev1 ~]$ python --version
Python 3.6.4

My python got upgraded unexpectedly.

**Comment by dnadeau4** [comment]
@sashakames That should not happens,  the files for linux python 2.7 are here.
https://anaconda.org/conda-forge/cdutil/files

linux-64/cdutil-8.0-py27_1.tar.bz2

```
conda create -n cdutil -c conda-forge cdutil
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /software/anaconda2/envs/py22:

The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py27_0         conda-forge
    ca-certificates: 2018.4.16-0           conda-forge
    cdat_info:       8.0-py27_0            conda-forge
    cdms2:           3.0-py27_6            conda-forge
...
```

**Comment by doutriaux1** [comment]
@dnadeau4 @sashakames I think this `feature` depends on anaconda version. I noticed that ost of the time we do bring in python 3.6 unless we specify python=2, but on some system (newer conda?) it does bring python 2 as expected.

**Comment by jasonb5** [comment]
If this is still an issuem, please reopen.
