### ISSUE TITLE
small problem with conda build on osx high sierra

### ISSUE THREAD

**Issue by philrasch** [CDAT/cdat#2203]
_ I just tried an install using conda channels using the commands
conda create -n uvcdat-2.12 uvcdat -c conda-forge -c uvcdat
source activate uvcdat-2.12

The problem occcured on an up to date version of osx high sierra, after doing a "conda update conda", and making sure there were no previous installs on my path

It built fine, but after activation, when I tried execute a simple python script that just imports matplotlib, I got an error attributed to the version of the six module that is installed. This issue identifies the problem, and one solution. Maybe it will help others.

Phil
_

bash-3.2$ python pjr.py
Traceback (most recent call last):
  File "pjr.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/matplotlib/__init__.py", line 195, in <module>
    "Matplotlib requires six>=1.10; you have %s" % six.__version__)
ImportError: Matplotlib requires six>=1.10; you have 1.7.2

_So I looked for the versions of the six package built in the environment, and saw this._

(uvcdat-2.12) bash-3.2$ find /Users/d3x345/anaconda/envs/uvcdat-2.12 -name 'six*'
/Users/d3x345/anaconda/envs/uvcdat-2.12/conda-meta/six-1.11.0-py27_1.json
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/pip/_vendor/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/packages/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/packages/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/pip/_vendor/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/sklearn/externals/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/sklearn/externals/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/six-1.11.0-py2.7.egg-info
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/urllib3/packages/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/urllib3/packages/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/setuptools/_vendor/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/setuptools/_vendor/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/pkg_resources/_vendor/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/pkg_resources/_vendor/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/scipy/_lib/six.pyc
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/scipy/_lib/six.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/zmq/utils/sixcerpt.py
/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/zmq/utils/sixcerpt.pyc

_I looked through the versions of six listed above, and the problem appears to be that the site-packages version is out of date. The version number in that file is 1.7.2. If I remove it, then retry the simple script it fails. If I then ask conda to install six, it does so, and the script works. This output shows the evidence.

First I looked it the file, then disabled it._
(uvcdat-2.12) bash-3.2$ less /Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/six.py
(uvcdat-2.12) bash-3.2$ mv /Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/six.py /Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/six.py_off

_Deleted all the .pyc files and tested my script._
(uvcdat-2.12) bash-3.2$ find /Users/d3x345/anaconda/envs/uvcdat-2.12 -name '*.pyc' -delete
(uvcdat-2.12) bash-3.2$ pwd
/Users/d3x345/Dropbox/Python/Code
(uvcdat-2.12) bash-3.2$ !py
python pjr.py
Traceback (most recent call last):
  File "pjr.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/Users/d3x345/anaconda/envs/uvcdat-2.12/lib/python2.7/site-packages/matplotlib/__init__.py", line 104, in <module>
    import six
ImportError: No module named six

_Then installed six_

(uvcdat-2.12) bash-3.2$ conda install six
Solving environment: done

## Package Plan ##

  environment location: /Users/d3x345/anaconda/envs/uvcdat-2.12

  added / updated specs: 
    - six

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.1.18          |           py27_0         143 KB

The following packages will be UPDATED:

    certifi:         2018.1.18-py27_0 conda-forge --> 2018.1.18-py27_0     
    openssl:         1.0.2n-0         conda-forge --> 1.0.2o-h26aff7b_0    
    six:             1.11.0-py27_1    conda-forge --> 1.11.0-py27h7252ba3_1

The following packages will be DOWNGRADED:

    ca-certificates: 2018.1.18-0      conda-forge --> 2017.08.26-ha1e5d58_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
certifi 2018.1.18: ############################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

_Retesting, shows it works_

(uvcdat-2.12) bash-3.2$ python pjr.py
(uvcdat-2.12) bash-3.2$

**Comment by doutriaux1** [comment]
Hi @philrasch this is is a known problem due to conflict between zlib that vtk-cdat was built against and zlib that matplotlib 2.1 was built against.
This is addressed in the cdat nightlies and also in the the new version of cdat due tomorrow.
If you do not mind waiting until tomorrow then the nesest version will fix this.
if you cannot wait, usually simply doing a `pip install six` seems to fix the issue.

**Comment by jasonb5** [comment]
Sounds like this was fixed. If this is still an issue, please try with the latest CDAT (8.2.1).
