### ISSUE TITLE
No module named 'xmgrace' in cdat8

### ISSUE THREAD

**Issue by arulalant** [CDAT/cdat#2206]
Hai,

I couldnt import xmgrace in new cdat8 release.
How can I install it ?

(cdat8) arulalan@arulalan:~$ python
Python 3.6.5 | packaged by conda-forge | (default, Mar 29 2018, 23:19:37) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmgrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'xmgrace'

Thanks,
Arulalan.T

**Comment by dnadeau4** [comment]
@arulalant I created a package in our `nightly` branch.   Git it  a try and let me know if it works for you...  
 * `source activate cdat8`
 * `conda install -c uvcdat/label/nightly  xmgrace`

**Comment by arulalant** [comment]
(cdat8) arulalan@arulalan:~$ conda install -c uvcdat/label/nightly xmgrace
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - xmgrace
Use "conda info <package>" to see the dependencies for each package.

I am getting the above error.

**Comment by aashish24** [comment]
looks like typical conda error with versions mismatch. Was there anything else showing up in the error message..the list of packages in conflict?

**Comment by arulalant** [comment]
No other message is showing up with the error.
I have upgraded the conda version from 4.1.12 -> 4.5.0. Will that make any problem? I couldn't install cdat8 with older conda version since then I upgraded to latest version.

**Comment by doutriaux1** [comment]
@arulalant 
```
conda install -c uvcdat xmgrace
```

Should work. Please let me know.

**Comment by doutriaux1** [comment]
@arulalant ok I will rebuild xmgrace give me one hour.

**Comment by doutriaux1** [comment]
@arulalant ok it should be ready to go 
```
conda install -c conda-forge -c cdat xmgrace
```

Please let me know.

**Comment by arulalant** [comment]
@doutriaux1 Thanks. It works now. Let me close this issue

**Comment by arulalant** [comment]
@doutriaux1 Could you please add xmgrace into default package of upcoming cdat8versions.
When I try to install it inside cdat8.1, conda asking me to downgrade some of the python packages which I do not want to do.

Thanks.

**Comment by shahid-sattar** [comment]
Hi @doutriaux1 @arulalant 
I am trying to install xmgrace via conda but it is not working from any of the given options.
A previous post suggest using:
conda install -c conda-forge -c cdat xmgrace

which is also not working.
Can anyone suggest some solution.

**Comment by arulalant** [comment]
Hai @shahid-sattar,
It is working for me. Make sure you pre-installed xmgrace system software.
For eg, in my MAC, /usr/local/bin/xmgrace which is installed homebrew cmd.
In other linux distro, you can install xmgrae software via apt-get or rpm cmd.
