### ISSUE TITLE
Different plot quality - anaconda2-5.x+cdat8 vs CDAT-2.4.1binary

### ISSUE THREAD

**Issue by puneet336** [CDAT/cdat#2209]
Hi,
I am trying to run a python plotting script which gives me different quality of same plot.
I have uploaded the image qualities & the relevant std err/out messages while running the script.
(please ignore Traceback errors, i had killed the script after getting few image files)

The list of python modules used are as - 
```
import numpy as np  # Numerical python
import matplotlib.pyplot as plt  # General ploting
import matplotlib.cm as mpl_cm  # Colour maps
import matplotlib.ticker as mticker
import iris, json, os, sys, numpy, time
import iris.quickplot as qplt # Quickplot for Iris Cubes
#from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
from mpl_toolkits.basemap import Basemap
import cartopy.crs as ccrs  # Cartography module used with Iris
import cartopy.feature as cfeature
from numpy import linspace
from numpy import meshgrid
```
for the setup generating better images (attached - okay1.png, okay1.log), version of module within [prebuild](https://github.com/CDAT/cdat/releases/download/v2.4.1/UV-CDAT-2.4.1-CentOS-6.5-RedHat6-64bit.tar.gz)- 
numpy - 1.14.0
matplotlib - 1.5.1
iris - 2.1.0
cartopy - u'0.16.0'

For bad quality setup (issue1.log, issue1.png)- 
numpy -'1.14.0'
matplotlib - '2.2.2'
iris - '1.13.0'
cartopy - u'0.16.0'

Please do let me know if i can provide more information on this issue for a fix.

[issue1.log](https://github.com/CDAT/cdat/files/2162576/issue1.log)
![issue1](https://user-images.githubusercontent.com/5935825/42268564-788050cc-7f99-11e8-9e6e-590a81c0e8b9.png)
[okay1.log](https://github.com/CDAT/cdat/files/2162577/okay1.log)
![okay1](https://user-images.githubusercontent.com/5935825/42268566-78df80f6-7f99-11e8-9e36-c1abd6e7455d.png)

**Comment by doutriaux1** [comment]
Hi,

I'm not sure how this is related to CDAT. You seem to be using cartopy/matplotlib. I recommend you post of their lists.

C.

**Comment by jasonb5** [comment]
This issue is not related to CDAT.
