### ISSUE TITLE
cdat - install from channel - many test failures -- Library not loaded: @rpath/libnetcdf.11.dylib( both linux and macOS)

### ISSUE THREAD

**Issue by muryanto1** [CDAT/cdat#2212]
``macos_cdat_latest_channel_py3 - https://circleci.com/gh/CDAT/cdat/5189
 
install:
   conda create -n cdat_latest_channel_py3 -c cdat/label/v80 -c conda-forge -c cdat python=3.6 cdat
 
   source activate cdat_latest_channel_py3; 
   conda install -c conda-forge -c cdat -c pcmdi/label/nightly -c pcmdi nose coverage image-compare pcmdi_metrics cia easydev nbsphinx mesalib; 
   source deactivate"
 
macos_cdat_latest_channel_py2 - https://circleci.com/gh/CDAT/cdat/5184
 
Lots of test failures due to:
b'ERROR: Failure: ImportError (dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdtime.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib'
b'  Referenced from: /Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdtime.cpython-36m-darwin.so'
b'  Reason: image not found)'
b'----------------------------------------------------------------------'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest'
b'    raise self.exc_val.with_traceback(self.tb)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName'
b'    addr.filename, addr.module)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath'
b'    return self.importFromDir(dir_path, fqname)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir'
b'    mod = load_module(part_fqname, fh, filename, desc)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/imp.py", line 235, in load_module'
b'    return load_source(name, filename, file)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/imp.py", line 172, in load_source'
b'    module = _load(spec)'
b'  File "<frozen importlib._bootstrap>", line 684, in _load'
b'  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked'
b'  File "<frozen importlib._bootstrap_external>", line 678, in exec_module'
b'  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed'
b'  File "/Users/distiller/project/workdir/genutil/tests/test_genutil_udunits2_additions.py", line 1, in <module>'
b'    import genutil'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/genutil/__init__.py", line 5, in <module>'
b'    from .grower import grower  # noqa'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/genutil/grower.py", line 3, in <module>'
b'    import cdms2 as cdms'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdms2/__init__.py", line 20, in <module>'
b'    from .cdmsobj import CdArray, CdChar, CdByte, CdDouble, CdFloat, CdFromObject, CdInt, CdLong, CdScalar, CdShort, CdString  # noqa'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdms2/cdmsobj.py", line 5, in <module>'
b'    from . import cdmsNode'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdms2/cdmsNode.py", line 10, in <module>'
b'    import cdtime'
b'ImportError: dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdtime.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib'
b'  Referenced from: /Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/cdtime.cpython-36m-darwin.so'
b'  Reason: image not found'

**Comment by dnadeau4** [comment]
I moved the `cdtime` label from v80 to v80netcdf11.   That was moved from conda-forge by @doutriaux1 but not sure it it is needed anymore.

**Comment by doutriaux1** [comment]
@dnadeau4 it it works again like that then fine, I can't remember exactly why I had to do a `v80` label, but it was around the time you were upgrading the compilers. It might be fixed now and unncessary then. @muryanto1 does this fix the issue?

**Comment by muryanto1** [comment]
I verified that from our nightly run, Denis' changes fix the issue, not seeing "Library not loaded: @rpath/libnetcdf.11.dylib'" anymore.

**Comment by doutriaux1** [comment]
@muryanto1 the install from yaml still works?

**Comment by doutriaux1** [comment]
@muryanto1 this is why I add cdtime in a special `v80` channel. I'll try to fix the yamls...
