### ISSUE TITLE
macos_nightly_py2 nightly -- No module named vtkIOFFMPEGPython

### ISSUE THREAD

**Issue by muryanto1** [CDAT/cdat#2214]
``
======================================================================
ERROR: Failure: ImportError (No module named vtkIOFFMPEGPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/distiller/project/workdir/vcs/tests/test_vcs_vectors_warp.py", line 1, in <module>
    import basevcstest
  File "/Users/distiller/project/workdir/vcs/tests/basevcstest.py", line 5, in <module>
    import vcs
  File "/Users/distiller/project/workdir/vcs/vcs/__init__.py", line 102, in <module>
    from .utils import *  # noqa
  File "/Users/distiller/project/workdir/vcs/vcs/utils.py", line 39, in <module>
    import vtk
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/vtk/__init__.py", line 95, in <module>
    from .vtkIOFFMPEG import *
  File "/Users/distiller/project/workdir/miniconda/envs/nightly_py2/lib/python2.7/site-packages/vtk/vtkIOFFMPEG.py", line 9, in <module>
    from vtkIOFFMPEGPython import *
ImportError: No module named vtkIOFFMPEGPython
----------------------------------------------------------------------
Ran 1 test in 0.001s

**Comment by muryanto1** [comment]
macos_nightly_py2 -- https://circleci.com/gh/CDAT/cdat/5318
vcs -- all testcases FAILED
dv3d -- all testcases FAILED
thermo -- all testcases FAILED
vcsaddons -- all testcases FAILED
wk -- all testcases FAILED 
tests failed with stack trace shown above.

**Comment by muryanto1** [comment]
tests are also failing with similar stack trace in macos_cdat_latest_channel_py3 -- https://circleci.com/gh/CDAT/cdat/5330
and also macos_cdat_latest_channel_py2 -- https://circleci.com/gh/CDAT/cdat/5322

For example, thermo tests are failing:

b'======================================================================'
b'======================================================================'
b"ERROR: Failure: ModuleNotFoundError (No module named 'vtkIOFFMPEGPython')"
b"ERROR: Failure: ModuleNotFoundError (No module named 'vtkIOFFMPEGPython')"
b'----------------------------------------------------------------------'
b'----------------------------------------------------------------------'
b'Traceback (most recent call last):'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/vtkIOFFMPEG.py", line 5, in <module>'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/vtkIOFFMPEG.py", line 5, in <module>'
b'    from .vtkIOFFMPEGPython import *'
b'    from .vtkIOFFMPEGPython import *'
b'ImportError: dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/vtkIOFFMPEGPython.so, 2): Library not loaded: @rpath/libavformat.58.dylib'
b'ImportError: dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/vtkIOFFMPEGPython.so, 2): Library not loaded: @rpath/libavformat.58.dylib'
b'  Referenced from: /Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/libvtkIOFFMPEG-8.1.1.dylib'
b'  Reason: image not found'
b'  Referenced from: /Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/libvtkIOFFMPEG-8.1.1.dylib'
b'  Reason: image not found'
b'During handling of the above exception, another exception occurred:'
b'During handling of the above exception, another exception occurred:'
b'Traceback (most recent call last):'
b'Traceback (most recent call last):'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest'
b'    raise self.exc_val.with_traceback(self.tb)'
b'    raise self.exc_val.with_traceback(self.tb)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName'
b'    addr.filename, addr.module)'
b'    addr.filename, addr.module)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath'
b'    return self.importFromDir(dir_path, fqname)'
b'    return self.importFromDir(dir_path, fqname)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir'
b'    mod = load_module(part_fqname, fh, filename, desc)'
b'    mod = load_module(part_fqname, fh, filename, desc)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/imp.py", line 235, in load_module'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/imp.py", line 235, in load_module'
b'    return load_source(name, filename, file)'
b'    return load_source(name, filename, file)'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/imp.py", line 172, in load_source'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/imp.py", line 172, in load_source'
b'    module = _load(spec)'
b'    module = _load(spec)'
b'  File "<frozen importlib._bootstrap>", line 684, in _load'
b'  File "<frozen importlib._bootstrap>", line 684, in _load'
b'  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked'
b'  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked'
b'  File "<frozen importlib._bootstrap_external>", line 678, in exec_module'
b'  File "<frozen importlib._bootstrap_external>", line 678, in exec_module'
b'  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed'
b'  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed'
b'  File "/Users/distiller/project/workdir/thermo/tests/test_thermo_basic.py", line 2, in <module>'
b'    import thermo,vcs,cdms2'
b'  File "/Users/distiller/project/workdir/thermo/tests/test_thermo_no_coredump.py", line 2, in <module>'
b'    import thermo,vcs,cdms2'
b'  File "/Users/distiller/project/workdir/thermo/lib/thermo.py", line 6, in <module>'
b'  File "/Users/distiller/project/workdir/thermo/lib/thermo.py", line 6, in <module>'
b'    import vcs'
b'    import vcs'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vcs/__init__.py", line 102, in <module>'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vcs/__init__.py", line 102, in <module>'
b'    from .utils import *  # noqa'
b'    from .utils import *  # noqa'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vcs/utils.py", line 39, in <module>'
b'    import vtk'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vcs/utils.py", line 39, in <module>'
b'    import vtk'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/__init__.py", line 95, in <module>'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/__init__.py", line 95, in <module>'
b'    from .vtkIOFFMPEG import *'
b'    from .vtkIOFFMPEG import *'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/vtkIOFFMPEG.py", line 9, in <module>'
b'  File "/Users/distiller/project/workdir/miniconda/envs/cdat_latest_channel_py3/lib/python3.6/site-packages/vtk/vtkIOFFMPEG.py", line 9, in <module>'
b'    from vtkIOFFMPEGPython import *'
b'    from vtkIOFFMPEGPython import *'
b"ModuleNotFoundError: No module named 'vtkIOFFMPEGPython'"
b"ModuleNotFoundError: No module named 'vtkIOFFMPEGPython'"
b'----------------------------------------------------------------------'
b'----------------------------------------------------------------------'
b'Ran 1 test in 0.001s'
b'Ran 1 test in 0.001s'
b'FAILED (errors=1)'
b'FAILED (errors=1)'
Ran 2 tests, 2 failed (0.00% success)
Failed tests:
	 tests/test_thermo_basic.py
	 tests/test_thermo_no_coredump.py
Traceback (most recent call last):
  File "run_tests.py", line 237, in <module>
    file1, file2, diff = findDiffFiles(result["log"])
  File "run_tests.py", line 84, in findDiffFiles
    while log[i].find("Source file") == -1 and i > -N:
TypeError: a bytes-like object is required, not 'str'

**Comment by doutriaux1** [comment]
@muryanto1 I can reproduce this on my mac. Working on it.

**Comment by muryanto1** [comment]
I verified that Charles' fixes in cdat fixed this issue from 08/27 nightly.
https://circleci.com/gh/CDAT/cdat/5547
