### ISSUE TITLE
Installing cdat8 from conda channels fails

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/cdat#2220]
I tried to install using a yml file file on linux using:
And got following:
(uvcdat) bash-4.1$ conda env create -n cdat8 -f cdat-v80_py2.Linux.yaml 
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: .
NoPackagesFoundError: Packages missing in current linux-64 channels: 
  - vtk-cdat 8.0.1.8.0 py27_1
  - intel-openmp 2018.0.0 8
  - mkl 2018.0.2 1
  - numpy 1.14.2 py27hdbf6ddf_1
  - scipy 1.0.1 py27hfc37229_0

I suspect that these builds were removed somehow. I think we should fix the ymls.
By the way, the 'conda create -n cdat8 -c cdat/label/v80 -c conda-forge -c cdat python=2.7 cdat' works until I got this error when creating env...

Linking packages ...
[spyder-kernels      ]LinkError: Link error: Error: post-link failed for: conda-forge::nb_conda_kernels-2.2.0-py27_1000

**Comment by doutriaux1** [comment]
@muryanto1 where are we again with the updated yaml files?

**Comment by muryanto1** [comment]
Hi Charles,
With the current yaml files under validateNightly branch, install works,
But testcases failed.
Example:
https://circleci.com/gh/CDAT/cdat/7980
(don’t look at cdms, look at others)

Lina

**Comment by muryanto1** [comment]
This is the latest test run result from 'validateNightly' branch:
https://circleci.com/gh/CDAT/cdat/8011#artifacts/containers/0
you have to go to each test suite to see the failures.

**Comment by muryanto1** [comment]
Example of failure:
https://8011-6660536-gh.circle-artifacts.com/0/macos_cdat-v80-nox_py3/cdutil-tests_html/test_cdutil_times.html
ImportError: dlopen(/Users/distiller/project/workdir/miniconda/envs/cdat-v80-nox_py3/lib/python3.6/site-packages/cdtime.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.13.dylib

**Comment by doutriaux1** [comment]
I fixed the yamls today, I'm letting the test suite run tonight and it should be updated tomorrow.

**Comment by jasonb5** [comment]
Try the latest CDAT (8.2.1). If the issue still exists, please open a new issue.
