### ISSUE TITLE
cdms2 build fails in conda 4.6.x due to ESMF issue

### ISSUE THREAD

**Issue by alaniwi** [CDAT/cdat#2225]
cdms2 build is failing in conda 4.6.x because of an ESMF dependency issue which has been raised at https://github.com/conda-forge/esmf-feedstock/issues/35

Opening this issue here so that cdms2 developers are aware of the issue linked above, and can watch to see whether it is fixed or whether there is any need to work around it in cdms2.

**Comment by doutriaux1** [comment]
@alaniwi if you use the nightly it should be fixed:
`conda create -n nightly -c cdat/label/nightly -c conda-forge cdat`

Alternatively you can downgrade conda first
`conda install -n base -f 'conda<4.6'`

Please let us know if either of these solution help.

@dnadeau4 any other idea?

**Comment by alaniwi** [comment]
Thanks. Yes, it's known that downgrading conda seems to solve it (though it has already caught people out using 4.6.x). I sent you a link on Slack to the channel where it was being discussed.

**Comment by xylar** [comment]
This PR should fix the issue going forward: https://github.com/conda-forge/esmf-feedstock/pull/36

**Comment by dnadeau4** [comment]
@alaniwi I worked on this all weekend a week ago and you can now install cdms 3.1.2 with conda 4.6.2
```
conda install -c conda-forge cdms2 libcdms
```

Note: libcdms is not necessary, but ensure that it is not downgraded to 3.0.1 due to openssl 1.1 dependency.  I unpinned ESMF from cdms 3.1.2 since I new this issue would be coming faster than ESMF would update their package.

**Comment by alaniwi** [comment]
@dnadeau4 Thank you -- I'll let people know. (Sorry to hear that it took all your weekend!)

**Comment by jasonb5** [comment]
Closing as it looks like this was solved.
