### ISSUE TITLE
readline or curses problem with CDAT 8.0 (python 2 version) ?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat#2226]
This problem is a bit hard to describe, but now that I'm running more tests on 8.0, I have found out that I **can't edit lines correctly on the python prompt**. The strange thing is that I have this problem with the python 2 version, but it's working fine on the python 3 version 

I have pasted below what I get when I type: 123 `<CR>` 456 `<CR>` 789 `<CR>` `<UParrow>` `<UParrow>` `<UParrow>` `<CR>` abcde `<LEFTarrow>` `<LEFTarrow>` `<LEFTarrow>` X `<CR>`

Thanks for finding a workaround in 8.0 (python 2) if possible, and making sure this does not append in the next release. I'll try to install the nightly on the same server and see if I have the same problem

```
(cdat-8.0_py2) jypeter@obelix4 - ...jypeter - 50 >echo $term
xterm
(cdat-8.0_py2) jypeter@obelix4 - ...jypeter - 51 >echo $TERM
xterm
(cdat-8.0_py2) jypeter@obelix4 - ...jypeter - 52 >python
Python 2.7.15 | packaged by conda-forge | (default, Oct 12 2018, 14:10:50)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 123
123
>>> 456
456
>>> 789
789
>>> 789456123
123
>>> abcdeXcde
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'abXcde' is not defined
>>>
```

**Comment by jasonb5** [comment]
Closing as python2 is no longer supported and python3 appears to be working.
