### ISSUE TITLE
CDAT Support on Cori and LC

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/cdat#2233]
Hi, @doutriaux1 There are a couple of reports that CDAT support is needed for Cori since Edison was down..Also support/maintenance of CDAT on LC is also needed..I suggested the users to use e3sm_unified as a work around on Cori coz both have access to e3sm_unified.

**Comment by doutriaux1** [comment]
@chengzhuzhang cdat is on cori by itself but you need to be in the uvcdat group. If you give me your nersc username i cvan ask to have you added.

**Comment by chengzhuzhang** [comment]
Thank you @doutriaux1! would you please add hyma and chengzhu on Cori?

**Comment by jasonb5** [comment]
@chengzhuzhang Is there anything outstanding with this issue or may I close it? Thanks!

**Comment by chengzhuzhang** [comment]
Hi @jasonb5 thanks for tracking it. I don't have a specific issue now, but in general I was wondering do we still support the uvcdat group at Cori?

**Comment by jasonb5** [comment]
I'm not sure, @muryanto1 @downiec are we still providing support to the group at Cori?

**Comment by downiec** [comment]
I believe @sterlingbaldwin may be more familiar with this question. I'm not sure the if we are still providing support to the group.

**Comment by chengzhuzhang** [comment]
Thank you guys. Since the cdat installation was made much easier now, the support on Cori and LC maybe not needed any more. I guess we can re-visit problem when requests arrive.
