### ISSUE TITLE
CDAT 8.2.1 Release

### ISSUE THREAD

**Issue by jasonb5** [CDAT/cdat#2255]
Use this issue to track 8.2.1 release progress.

- [x] Build CDAT RC 8.2.1.rc1
- [x] update readthedocs env file for cdms and vcs
- [x] Build CDAT RC 8.2.1.rc2
- [x] Pass testing
- [x] Build CDAT Release
- [x] Update documentation

List might change.

**Comment by jasonb5** [comment]
Just noting these non-blocking issues.

- https://github.com/CDAT/dv3d/issues/30
- https://github.com/CDAT/vcsaddons/issues/54

**Comment by muryanto1** [comment]
Test logs are:
https://app.circleci.com/pipelines/github/CDAT/cdat_validate_release/19/workflows/aec34ba1-3cee-46a4-bd6a-44c370afe883
