### ISSUE TITLE
Update roadmap?

### ISSUE THREAD

**Issue by Xunius** [CDAT/cdat#2259]
Hi,

I noticed that the roadmap info (https://github.com/CDAT/cdat/wiki/Roadmap-to-Release) is pretty old and stops at 2017. I wonder is there an update vision of CDAT, where is it heading in the future?

Thanks

**Comment by downiec** [comment]
@Xunius yes we have a vision, but it hasn't been posted there and is still being developed. Thanks for bringing that to our attention, we are still working on updating all the documentation in the wiki and elsewhere as the previous main developers have moved on and there's a lot of cleanup left to do to the legacy documentation and stale issues.

**Comment by downiec** [comment]
Plans for CDAT have changed and the future is uncertain, currently the project is in maintenance mode. The current roadmap has been updated to reflect this. https://github.com/CDAT/cdat/wiki/Roadmap-to-Release
