### ISSUE TITLE
Possibility to install cdms2/cdutil from source?

### ISSUE THREAD

**Issue by jservonnat** [CDAT/cdat#2263]
Hello UV-CDAT team,
glad to be back ;). I'm currently trying to work with my computing center on a python installation with cdms2 and cdutil. At the moment, they don't want to install the packages with conda and want to compile themselves for security reasons.
Is there a way to get the sources and not install cdat with conda?
Cheers

**Comment by doutriaux1** [comment]
@jservonnat just use the recipe that is pacakged with the conda packages. I believe the recipe is also part of the cdms/cdutil repo.

**Comment by jservonnat** [comment]
@doutriaux1 do you think that using https://github.com/CDAT/cdat/blob/master/conda/cdat-v82_py3.7.Linux.yaml could do the job?

**Comment by doutriaux1** [comment]
@jservonnat 
build recipe: https://github.com/CDAT/cdms/blob/master/recipe/build.sh
dependencies: https://github.com/CDAT/cdms/blob/master/recipe/meta.yaml.in

You will have to follow the similar links for our own dependencies: libcdms, libcf, libdrs (you do not need the 'f' version it's for fortran and only used for pcmdi's scientist old file format), and cdtime. The rest should be standard and already in your env.

**Comment by doutriaux1** [comment]
If you run into issues I'm sure @jasonb5, @painter1  or @muryanto1 can help you

**Comment by downiec** [comment]
No further responses. Closing the issue.
