### ISSUE TITLE
Issues and questions using VCS on MacOS

### ISSUE THREAD

**Issue by LDuan3008** [CDAT/cdat#2264]
Hi all,

I installed the latest CDAT-8.2.1 on my MAC (10.15.7) based on instructions here: https://github.com/CDAT/cdat/wiki/Installing-Previous-CDAT-Versions. While CDAT works fine for me for most purposes, I do have several issues using it and I cannot find answers by googling: 

(1) I am running Python/CDAT using Visual Studio Code. The `a.plot(b,array)` command cannot open canvas window for me. When I use the terminal instead, it shows `<vcs.displayplot.Dp object at 0x7fc30b44e130>`. Also the interact mode does not take effect. I am wondering if there is anything missing here? 

(2) I also want to use the 3D plot feature of VCS. One thing I noticed is that the CDAT logo cannot be turned off using `v.drawlogooff()`. At the same time, the 3D results can only be saved to *.png format, and other formats (e.g., *.svg, *.pdf, *.ps) cannot work correctly. Is this correct? 

(3) I am pretty new to the 3D plotting, and I am wondering what's the difference between vtk-cdat, which is installed by CDAT, and the vtk module. Can I output the VCS results (e.g., volume rendering) to some vtk-compatible format for loading outside CDAT? 

Thanks very much!

++++++

My conda info is attached below:

```
     active environment : cdat
    active env location : /opt/anaconda3/envs/cdat
            shell level : 2
       user config file : /Users/lei3008/.condarc
 populated config files : /Users/lei3008/.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/lei3008/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/lei3008/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

**Comment by downiec** [comment]
HI @LDuan3008 

I'm not sure what specific command you used to create your CDAT env, but I tried creating one from scratch using the installation steps documented here: https://github.com/CDAT/cdat/wiki/Install

Then after I created the environment, I opened a VSCode terminal, activated the environment and ran the following commands for a test plot, to see whether the canvas window opens:

```
# Command from install instructions
conda create -y -n cdat -c conda-forge -c cdat/label/v8.2.1 cdat "libnetcdf=*=mpi_openmpi_*" "mesalib=17.3.9" "python=3.7"
conda activate cdat
python
# Code below entered in python shell for test plot
>>>import vcs, MV2
>>>x=vcs.init()
>>> x.open()
>>> x.plot(MV2.array([[1,2,3],[4,5,6]]))
```

With the test above, I was able to see the test plot canvas display correctly, however this was by using a terminal in VSCode. I'm not sure how you are set up in your case, what your plot looks like or how you created the conda environment. If you'd like to narrow down where the issue may be, could you try the steps above and see if the same test works for you?

In regards to your 2nd question, I could try to replicate the issue if you have an example code that I could use to test and see if the logo won't go away on my end too. I'd like to confirm if this is a bug or an issue related to the above.

As far as your 3rd question, I am not sure of the answer and would have too research into it but I will post more if I find out.

Thanks!

**Comment by downiec** [comment]
Did not receive further response, closing the issue for now.
