### ISSUE TITLE
ghostscript and others not built on mac

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#426]
> > > x.gif("hi")
> > > sh: gs: command not found
> > > sh: pnmflip: command not found
> > > sh: ppmquant: command not found
> > > sh: ppmtogif: command not found
> > > 'hi.gif'

Probably not that important since we are rewriting vcs and it wont use this.

**Comment by doutriaux1** [comment]
@aashish24 2.3?

**Comment by aashish24** [comment]
2.3
